name: Promote Development to Production

on:
  workflow_dispatch:
    inputs:
      confirm_promotion:
        description: 'Type "promote" to confirm promotion to production'
        required: true
        type: string

jobs:
  validate-promotion:
    name: Validate Promotion Request
    runs-on: ubuntu-latest
    
    steps:
    - name: Validate confirmation
      run: |
        if [ "${{ github.event.inputs.confirm_promotion }}" != "promote" ]; then
          echo "Promotion cancelled. Please type 'promote' to confirm."
          exit 1
        fi
        echo "Promotion confirmed"

  promote-to-main:
    name: Promote Development Branch to Main
    runs-on: ubuntu-latest
    needs: validate-promotion
    environment: production
    
    steps:
    - name: Checkout development branch
      uses: actions/checkout@v4
      with:
        ref: copilot/fix-4d4f3236-5307-4aeb-bd6a-7814afa559ee
        fetch-depth: 0
        
    - name: Setup Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Merge development to main
      run: |
        git checkout main
        git merge --no-ff copilot/fix-4d4f3236-5307-4aeb-bd6a-7814afa559ee -m "chore: promote development to production"
        git push origin main
        
    - name: Create release tag
      run: |
        VERSION=$(date +%Y.%m.%d-%H%M%S)
        git tag -a "v$VERSION" -m "Release v$VERSION - promoted from development"
        git push origin "v$VERSION"
        echo "Created release tag: v$VERSION"